export { default as ChevronLeft } from './ChevronLeft'
export { default as ChevronRight } from './ChevronRight'
export { default as Home } from './Home'
export { default as İnfo } from './İnfo'
export { default as Search } from './Search'
export { default as X } from './X'